# Site settings
name: Johanes Arnold
email: johanesarnold@hotmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Backend Developer, PHP, Python, Startups, Agile, Pair Programming, AWS, MySQL"
skills: "Software Engineer (Backend) in Jakarta, Indonesia"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/johanesarnold/
  - title: instagram
    url: https://www.instagram.com/johanesarnold/
  #- title: twitter
  #  url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1c83a8
  primary-rgb: "33, 150, 243"
  secondary: 2c3e50
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
